### ISSUE TITLE
UET_PDS_REQ_FLAGS_* bits off-by-one

### ISSUE THREAD

**Issue by alexb-kt** [ultraethernet/uet-ref-prov#2]
In `uet_pkt_hdr.h` the `UET_PDS_REQ_FLAG_*` bits seem to be 1 bit too far to the left.

See also comment: https://github.com/ultraethernet/uec-transport-ref-prov/commit/dc07a1ed102e3545a7cdde2bc2782b7b09b06a4b#r139657699

**Comment by insanum** [comment]
Yes, all the header format structs are in the process of being updated.
