### ISSUE TITLE
uet_api.c  line 905  Code parameter passing error

### ISSUE THREAD

**Issue by zhanglianqing1990** [ultraethernet/uet-ref-prov#29]
uet_dealloc_msg_id(tx_desc->uet_ep->uet_domain->uet,&tx_desc->msg_id);
parameter &tx_desc->msg_id must be change to tx_desc->msg_id; 
Otherwise, it may cause "No Msg ID Available" Error.

**Comment by alexb-kt** [comment]
Ah, nice, I had commit f5cdf511554ad9341c73ab0063cd407b85ba120e in my tree but never got around to making a PR
