### ISSUE TITLE
CRC doesn't work

### ISSUE THREAD

**Issue by alexb-kt** [ultraethernet/uet-ref-prov#39]
From a brief surface look:
* IP total length is not updated when adding the 8 CRC bytes, so they look like Ethernet FCS and/or trailer past the IP packet
* it looks like the CRC is computed over the entire Ethernet frame (rather than just PDS header onwards)
* CRC tables are not initialized, so all CRC values are all-zeroes

**Comment by insanum** [comment]
I made a commit today that initializes the CRC table. I haven't yet retested.

**Comment by alexb-kt** [comment]
FYI I made some attempts at https://github.com/alexb-kt/uet-ref-prov/commits/alexb/crc-fixes/ but didn't get it working (CRC mismatches on Rx)

**Comment by insanum** [comment]
Great thanks. I'll take a look...
